# https://taskfile.dev

version: "3"

includes:
  docker:
    taskfile: Taskfiles/docker.yml

# Load environment-specific .env files
# Variables from files listed first take precedence over those in later files
# when the same variable is defined in multiple files
dotenv:
  - .env.docker.local
  - .env.docker
  - .env.local
  - .env.base

tasks:
  # Default task
  default:
    desc: List all tasks
    cmds:
      - task --list

  env:generate:
    desc: |
      Generate a .env file from .env.template by substituting environment variables loaded 
      from dotenv files via Task's dotenv feature.
    cmds:
      - envsubst < .env.template > .env