# https://taskfile.dev

version: "3"

# Load environment-specific .env file
dotenv: [ config/environment/.env.base ]
# dotenv: [ config/environment/.env.docker, config/environment/.env.base ]

includes:
  docker: docker/Taskfile.yml

tasks:
  # Default task
  default:
    desc: List all tasks
    cmds:
      - task --list

  env:generate:
    desc: Generate a new .env file
    cmds:
      - envsubst < .env.template > .env.test